apiVersion: v1
kind: Service
metadata:
  name: auth-user
spec:
  selector:
    app: auth-user
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-user
  template:
    metadata:
      labels:
        app: auth-user
    spec:
      containers:
        - name: app
          image: muhammadfadliku/deals-auth
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: secret
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DBNAME
              value: auth_user
          imagePullPolicy: Always